### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zoranzoki21**
https://phabricator.wikimedia.org/T202047

### CODE REVIEW

**Comment by Hutchy68** [comment]
Need to update your PR and from this point on, the installation will use registration only.

`wfLoadExtension( 'Purge' );`

**Comment by zoranzoki21** [comment]
> Need to update your PR and from this point on, the installation will use registration only.
> 
> `wfLoadExtension( 'Purge' );`

Sure, I will.

**Comment by zoranzoki21** [comment]
File already updated in #26, so I think that this pull request can be closed.

**Comment by Hutchy68** [comment]
Not the readme file

**Pull request closed without merging**
